### ISSUE TITLE
Add info on what the Snakefile does in hyperqueue example

### ISSUE THREAD

**Issue by samumantha** [coderefinery/snakemake_hackathon#13]
What are the tools used and the process that is described by the Snakefile?

**Comment by yetulaxman** [comment]
How about this: This is a life science example where raw sequencing data is mapped to reference data (using  bwa tool under the rule:  bwa_map). The resulting data (.bam files) is sorted (by samtool in the rule, samtools_sort) and indexed (by samtool in the rule, samtools_index) before variant calling. Variants are called (by bcftool untility tools in the rule:  bcftools_call) and finally plotted (in the rule: plot_quals). The raw reads are random tiny fastq files and may not have biological meaning.
